### ISSUE TITLE
Error on building

### ISSUE THREAD

**Issue by ArSd-g** [cd-Spidey/Custom-Recovery-Builder#6]
Hello,
I need to say i'm not a dev and i'm not so familiar with github...

"Run git clone https://github.com/ArSd-g/twrp_device_Oukitel_RT2_MT8788.git -b twrp-12.1 ./device/oukitel/rt2
Cloning into './device/oukitel/rt2'...
fatal: Remote branch twrp-12.1 not found in upstream origin
Error: Process completed with exit code 128."

What i'm doing wrong? Maybe you can build it for me according to my device tree? (untouched from https://github.com/twrpdtgen/twrpdtgen generated)

After a few noob tricks here is the log of my building attempt:
[logs_4.zip](https://github.com/cd-Spidey/Custom-Recovery-Builder/files/10836087/logs_4.zip)

Regards

laarSn

**Comment by cd-Spidey** [comment]
Hmmm. Sorry, untouch device tree from twrpdtgen is morel likely to fail, sad. You have to bringup/reconfigure the device tree base into your device information.

Also, make sure to use right manifest branch if you are building. You can visit TeamWin page to reference some tree how to properly configure your tree.

**Comment by cd-Spidey** [comment]
Also, while checking your device tree in your profile. You are using wrong branch in your own tree. You device tree use "main" as branch, why are you using "twrp-12.1" when building.
