### ISSUE TITLE
FAILED: out/target/product/bahamut_kddi/boot.img

### ISSUE THREAD

**Issue by plente00** [cd-Spidey/Custom-Recovery-Builder#7]
FAILED: out/target/product/bahamut_kddi/boot.img
/bin/bash -c "(out/host/linux-x86/bin/mkbootimg --kernel out/target/product/bahamut_kddi/kernel --ramdisk out/target/product/bahamut_kddi/ramdisk-recovery.img  --cmdline \"androidboot.hardware=qcom androidboot.memcg=1 lpm_levels.sleep_disabled=1 video=vfb:640x400,bpp=32,memsize=3072000 msm_rtb.filter=0x237 service_locator.enable=1 swiotlb=2048 loop.max_part=7 androidboot.usbcontroller=a600000.dwc3 oemboot.earlymount=/dev/block/platform/soc/1d84000.ufshc/by-name/oem:/mnt/oem:ext4:ro,barrier=1:wait,slotselect,first_stage_mount buildproduct=bahamut_kddi buildid=KUMANO-1.2.0-KDDI-211005-1354 panic_on_err=1 buildvariant=user twrpfastboot=1 buildvariant=eng\" --base 0x00000000 --pagesize 4096 --os_version 12 --os_patch_level 2099-12-31  --header_version 2 --ramdisk_offset 0x01000000 --tags_offset 0x00000100 --dtb device/sony/bahamut_kddi/prebuilt/dtb.img --output  out/target/product/bahamut_kddi/boot.img ) && (size=\$(for i in  out/target/product/bahamut_kddi/boot.img; do stat -c \"%s\" \"\$i\" | tr -d '\\n'; echo +; done; echo 0); total=\$(( \$( echo \"\$size\" ) )); printname=\$(echo -n \" out/target/product/bahamut_kddi/boot.img\" | tr \" \" +); maxsize=\$((     69431296-69632)); if [ \"\$total\" -gt \"\$maxsize\" ]; then echo \"error: \$printname too large (\$total > \$maxsize)\"; false; elif [ \"\$total\" -gt \$((maxsize - 32768)) ]; then echo \"WARNING: \$printname approaching size limit (\$total now; limit \$maxsize)\"; fi ) && (out/host/linux-x86/bin/avbtool add_hash_footer --image  out/target/product/bahamut_kddi/boot.img --partition_size   69431296 --partition_name boot  --prop com.android.build.boot.fingerprint:\$(cat out/target/product/bahamut_kddi/build_fingerprint.txt) --prop com.android.build.boot.os_version:12 )"
usage: mkbootimg [-h] [--kernel KERNEL] [--ramdisk RAMDISK] [--second SECOND]
                 [--dtb DTB]
                 [--recovery_dtbo RECOVERY_DTBO | --recovery_acpio RECOVERY_ACPIO]
                 [--cmdline CMDLINE] [--vendor_cmdline VENDOR_CMDLINE]
                 [--base BASE] [--kernel_offset KERNEL_OFFSET]
                 [--ramdisk_offset RAMDISK_OFFSET]
                 [--second_offset SECOND_OFFSET] [--dtb_offset DTB_OFFSET]
                 [--os_version OS_VERSION] [--os_patch_level OS_PATCH_LEVEL]
                 [--tags_offset TAGS_OFFSET] [--board BOARD]
                 [--pagesize {2048,4096,8192,16384}] [--id]
                 [--header_version HEADER_VERSION] [-o OUTPUT]
                 [--gki_signing_algorithm GKI_SIGNING_ALGORITHM]
                 [--gki_signing_key GKI_SIGNING_KEY]
                 [--gki_signing_signature_args GKI_SIGNING_SIGNATURE_ARGS]
                 [--gki_signing_avbtool_path GKI_SIGNING_AVBTOOL_PATH]
                 [--vendor_boot VENDOR_BOOT] [--vendor_ramdisk VENDOR_RAMDISK]
                 [--vendor_bootconfig VENDOR_BOOTCONFIG]
mkbootimg: error: argument --dtb: can't open 'device/sony/bahamut_kddi/prebuilt/dtb.img': [Errno 2] No such file or directory: 'device/sony/bahamut_kddi/prebuilt/dtb.img'
ninja: build stopped: subcommand failed.
03:21:33 ninja failed with: exit status 1
Error: Process completed with exit code 1.

**Comment by cd-Spidey** [comment]
Double check your device tree. It seems you set target for dtb prebuild, but dtb.img didn't exist at all.

Make sure dtb.img is in the prebuilt folder.
