### ISSUE TITLE
fixed for omni builds

### ISSUE THREAD

**Issue by U89-sk** [cd-Spidey/Custom-Recovery-Builder#9]
add sudo apt-get -y install libncurses5 libtinfo5

**Comment by cd-Spidey** [comment]
Alright.

It has been a long time since I built omni recovery. I didn't theres still omni devices still active.

**Comment by cd-Spidey** [comment]
You can try now, see if error still persist in omni builds.

**Comment by U89-sk** [comment]
Thank you for update 😇
